### ISSUE TITLE
Twice registered crash!

### ISSUE THREAD

**Issue by Kevadroz** [elix-x/Colourful-Blocks#17]
I don't know if this is duplicated because al the insuess have the same title, but I have a crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-18.jar)
  colorfulblocks (ColorfulBlocks-1.3.2-1.9.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.1.jar)
  SeasonsPreLoader (SeasonsAPI-1.1.3b.jar)
  BCModPlugin (zz-backpacks 1.9 - 3.0.10 beta.jar)
  CXLibraryCore (cxlibrary-1.0.0.jar)
  StreamsCoreMod (Streams-1.9-0.2.jar)
  FarseekCoreMod (Farseek-1.9-1.0.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 17/05/16 14:06
Description: Initializing game

java.lang.IllegalArgumentException: The name colorfulblocks:brush_eternalflames has been registered twice, for code.elix_x.coremods.colorfulblocks.items.ItemBrush@6d17a36e and code.elix_x.coremods.colorfulblocks.items.ItemBrush@50a38985.
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:425)
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:781)
    at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:243)
    at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:146)
    at code.elix_x.coremods.colorfulblocks.color.tool.ColoringToolsManager.init(ColoringToolsManager.java:56)
    at code.elix_x.coremods.colorfulblocks.ColorfulBlocksBase.init(ColorfulBlocksBase.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:765)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:425)
    at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:781)
    at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:243)
    at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:146)
    at code.elix_x.coremods.colorfulblocks.color.tool.ColoringToolsManager.init(ColoringToolsManager.java:56)
    at code.elix_x.coremods.colorfulblocks.ColorfulBlocksBase.init(ColorfulBlocksBase.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:765)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1249872392 bytes (1191 MB) / 2211299328 bytes (2108 MB) up to 2570715136 bytes (2451 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2554M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.1.1904 Optifine OptiFine_1.9_HD_U_B3 46 mods loaded, 46 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1904.jar) 
    UCHI    Forge{12.16.1.1904} [Minecraft Forge](forge-1.9-12.16.1.1904.jar) 
    UCHI    buildingbricks{1.9-2.0.1} [Building Bricks](BuildingBricks-1.9-2.0.1.jar) 
    UCHI    backpacks16840{3.0.10} [Backpacks!](zz-backpacks 1.9 - 3.0.10 beta.jar) 
    UCHI    JEI{3.3.3.197} [Just Enough Items](jei_1.9-3.3.3.197.jar) 
    UCHI    abyssalcraft{1.9.1.6} [AbyssalCraft](AbyssalCraft-1.9-1.9.1.6.jar) 
    UCHI    armorplus{1.11.0-1.9} [ArmorPlus](ArmorPlus1.11.0%281.9%29.jar) 
    UCHI    backlytra{1.9-0.0.1} [Backlytra](backlytra-1.9-0.0.1.jar) 
    UCHI    basemetals{2.2.1} [Base Metals](BaseMetals_1.9-2.2.1.jar) 
    UCHI    BetterAchievements{0.2.5.19} [Better Achievements](BetterAchievements-1.9-0.2.5.19.jar) 
    UCHI    blockdrops{1.0.0} [Block Drops](Block Drops-1.9-1.0.0.jar) 
    UCHI    BloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-38.jar) 
    UCHI    bookshelf{1.2.0.226} [Bookshelf](Bookshelf-1.9-1.2.0.237.jar) 
    UCHI    excore{1.5.3} [EXCore](Excore-1.5.3-1.9.jar) 
    UCHE    colorfulblocks{1.3.2} [Colorful Blocks](ColorfulBlocks-1.3.2-1.9.jar) 
    UCHI    customcrosshairmod{0.5-forge} [Custom Crosshair Mod](crosshairmod-v0.5-forge-mc1.9.jar) 
    UCHI    CustomBackgrounds{1.0} [Custom Backgrounds](CustomBackgrounds-MC1.9-1.1.jar) 
    UCHI    customnpcs{1.9.0_beta} [CustomNPCs](CustomNPCs_1.9.0_beta%2810may16%29.jar) 
    UCHI    cxlibrary{1.0.0} [CXLibrary](cxlibrary-1.0.0.jar) 
    UCHI    elementsofpower{0.7.7-alpha} [Elements of Power](ElementsOfPower-1.9-0.7.7-alpha %281%29.jar) 
    UCHI    EnhancedTools{1.9-1.0.0} [EnhancedTools](Enhanced Tools 1.9-1.0.0.jar) 
    UCHI    golems{4.02} [Extra Golems](ExtraGolems[1.9]-4.02 %281%29.jar) 
    UCHI    EzTimeKeeper{2.1.3} [Time Keeper](eztimekeeper-2.1.3.jar) 
    UCHI    Farseek{1.9-1.0} [Farseek](Farseek-1.9-1.0.jar) 
    UCHI    FEI{1.0.10} [Forever Enough Items](ForeverEnoughItems-1.0.10-1.9.jar) 
    UCHI    grapple_hooks{1.0.5} [Grapple Hooks](Grapple Hooks-1.9-1.0.5.jar) 
    UCHI    gravestone{1.2.4} [Gravestone](Gravestone Mod 1.2.4 .jar) 
    UCHI    HardcoreDarkness{1.8} [Hardcore Darkness](HardcoreDarkness-MC1.9-1.8.jar) 
    UCHI    InfernalMobs{1.6.9} [Infernal Mobs](InfernalMobs-1.9.jar) 
    UCHI    IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHI    journeymap{1.9-5.2.0b1} [JourneyMap](journeymap-1.9-5.2.0b1-unlimited.jar) 
    UCHI    jeresources{0.4.3} [Just Enough Resources](JustEnoughResources-1.9-0.4.3.jar) 
    UCHI    kk{0.7.7} [Kingdom Keys Re:Coded](Kingdom Keys Re Coded-1.9-0.7.7-19-universal.jar) 
    UCHI    mineralogy{3.0.0} [Mineralogy](Mineralogy_1.9.0-3.0.0.jar) 
    UCHI    modernmetals{0.9.2.3} [Modern Metals](ModernMetals-0.9.2.3.jar) 
    UCHI    MoreFurnaces{1.6.0} [More Furnaces](MoreFurnaces-1.6.0-MC1.9.jar) 
    UCHI    nethermetals{1.0.4} [Nether Metals](NetherMetals-1.0.4.jar) 
    UCHI    recipehandler{0.4} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.4%281.9%29.jar) 
    UCHI    NoPotionShift{1.0.0} [No Potion Shift](nopotionshift_1.9-1.0.0.jar) 
    UCHI    Quark{beta-18} [Quark](Quark-beta-18.jar) 
    UCHI    xreliquary{1.9-1.3.1.322} [Reliquary](Reliquary-1.9-1.3.1.322.jar) 
    UCHI    seasonsapi{1.1.3b} [Seasons API](SeasonsAPI-1.1.3b.jar) 
    UCHI    soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.9.jar) 
    UCHI    Streams{1.9-0.2} [Streams](Streams-1.9-0.2.jar) 
    UCHI    ultimate_unicorn_mod{1.4.12} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!](ultimate_unicorn_mod-1.9-1.4.12.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
colorfulblocks (ColorfulBlocks-1.3.2-1.9.jar)
  code.elix_x.coremods.colorfulblocks.core.ColorfulBlocksTransformer
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.1.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
SeasonsPreLoader (SeasonsAPI-1.1.3b.jar)
  mod.mindcraft.seasons.asm.Transformer
BCModPlugin (zz-backpacks 1.9 - 3.0.10 beta.jar)
  brad16840.common.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.0.0.jar)
  cubex2.cxlibrary.CoreModTransformer
StreamsCoreMod (Streams-1.9-0.2.jar)
  streams.core.StreamsClassTransformer
FarseekCoreMod (Farseek-1.9-1.0.jar)
  farseek.core.FarseekClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 365.19' Renderer: 'GeForce 710M/PCIe/SSE2'
    Launched Version: 1.9-forge1.9-12.16.1.1904
    LWJGL: 2.9.4
    OpenGL: GeForce 710M/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Super HD Kingdom Keys Resource Pack.zip (incompatible)
Current Language: Español (España)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
OptiFine Version: OptiFine_1.9_HD_U_B3
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 365.19
OpenGlRenderer: GeForce 710M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by Elix-x** [comment]
No. It's supposed to happen. You have two materials named eternalflames. Go to your generated.json and remove one of them.
